### ISSUE TITLE
Ember update

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#109]
Ember auf eine aktuelle LTS Version aktualisieren.

**Comment by schefbi** [comment]
@cravay Ich wollte Ember aktualisieren. Wenn ich `ember version`  mache zeigt es mir die Version. 3.26.1 an, aber ich habe gemeint das wir auf 3.19.0 laufen. Auch der Update Command funktioniert nicht. Wie müssen wir vorgehen? Wenn du Zeit hast schau es dir einmal an.

```
$ ember update --to 3.20.0
The specified command update is invalid. For available options, see `ember help`.
```

**Comment by cravay** [comment]
> Ich wollte Ember aktualisieren. Wenn ich `ember version` mache zeigt es mir die Version. 3.26.1 an, aber ich habe gemeint das wir auf 3.19.0 laufen.

Ich glaube `ember version` gibt die Version der global installierten "ember-cli" an. Die verwendete Version vom App ist im "package.json" zu sehen. Zurzeit ist das noch [3.0.0](https://github.com/bkd-mba-fbi/kursausschreibung/blob/master/package.json#L42).

> Auch der Update Command funktioniert nicht. Wie müssen wir vorgehen? Wenn du Zeit hast schau es dir einmal an.

Damit der Befehl `ember update` verfügbar ist muss er zuerst mit `ember install ember-cli-update` installiert werden. Es wird aber empfohlen den Befehl `ember-cli-update` (`npm install -g ember-cli-update`) und nicht das Addon zu verwenden.

Leider scheint das Update nicht richtig durchgeführt zu werden. Wahrscheinlich würde es gehen, wenn die Updates schrittweise angewandt werden. Ich kann mir das sonst am Wochenende mal anschauen.
