### ISSUE TITLE
Sehbehinderung Kurs Ampel-Status 

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#117]
Damit auch Personen mit einer Sehbehinderung den Status eines Kurs erkennen können müssen icons verwendet werden.

- Freie Plätze > pencil
- Garantierte Durchführung > check
- Anmeldefrist abgelaufen > clock
- Alle Plätze belegt > close
- Keine Online-Anmeldung möglich > ban

https://getuikit.com/docs/icon

**Comment by schefbi** [comment]
@fbufbi Was meinst du zu den icons? Ich habe bei Barriere Tests bemerkt, dass der Status für Sehbehinderte nicht ersichtlich ist in der Liste.

![image](https://user-images.githubusercontent.com/41326409/132522536-fc092efd-c0a5-475c-a53e-f94dc33b44b8.png)

**Comment by fbufbi** [comment]
@schefbi Finde ich gut! Ich nehme an, die Icons sind dann einfach im Kreis mit den bisherigen Farben drin (wie bei der Absenzenverwaltung).

**Comment by schefbi** [comment]
@fbufbi Korrekt
