### ISSUE TITLE
Dropdown Nationalities enthält Ziffer

### ISSUE THREAD

**Issue by AramLoosman** [bkd-mba-fbi/kursausschreibung#129]
Die Werte Nationalities enthalten vor der jeweiligen Nationalität eine ID/Laufnummer.

Frage: Muss diese Nummer in der Option enthalten sein (sie ist ja bereits als Value enthalten) oder könnte sie wenigstens am Ende erscheinen.
Aktuell ist es nicht möglich, durch Tippen zur gewünschten Nationalität zu gelangen, da die Zahlen zuerst kommen.

![image](https://user-images.githubusercontent.com/1239297/140948370-2ecd0b94-afa5-4ccf-b114-7bae209571f3.png)

**Comment by schefbi** [comment]
@AramLoosman Wir schauen uns das an. Es kommt so direkt von Backend. Ich werde prüfen ob wenn wird es weglassen der POST oder PUT immer noch funktioniert.

**Comment by schefbi** [comment]
@AramLoosman Test erfolgreich ist im aktuellen Build in der develop branch vorhanden.

Dropdown
![image](https://user-images.githubusercontent.com/41326409/141275010-e9d14661-c350-4eb8-ac5f-f719e43e009f.png)

Backend
![image](https://user-images.githubusercontent.com/41326409/141275231-b76eddcd-5241-40c6-bb9e-92dece1a8a10.png)
