### ISSUE TITLE
Anmeldedetail Ja/nein: "nein" als zusätzliche Option ermöglichen

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/kursausschreibung#174]
IST: Bei Anmeldedetails mit Typ Einfache Werte > Ja/Nein sind nur die Werte "ja" oder "leer" möglich. Es gibt keine Option "nein".
SOLL: Option "nein" soll auch vorhanden sein.
Beispiel: Immersive Ausbildung (bfb - BM2)

**Comment by schefbi** [comment]
@fbufbi Schon Heute wird ja und nein übermittelt. Eine Checkbox kennt nur ja oder nein. Leer gibt es nicht bei einer html Checkbox?

![Image](https://github.com/user-attachments/assets/c983a8ce-5e9d-49b7-862c-ae7d700302fd)

Mögliche Lösung: Wenn ja/nein im AD gewählt wird wird die im Kursmodul als Radiobutton oder Dropdown angezeigt.

**Comment by fbufbi** [comment]
@schefbi Ich glaube, das Problem ist die bisherige Darstellung- (die Übermittlung ist OK):
- Checkbox angewählt = ja
- Checkbox nicht angewählt ("leer") = nein => es ist nicht intuitiv, dass leer = nein; nein kann nicht ausgewählt werden

In dem Sinn ist die Darstellung mit Radio Buttons eine gute Lösung, da viel klarer und "nein" kann ausgewählt werden.
