### ISSUE TITLE
Anmeldung abschliessen mit Login Daten

### ISSUE THREAD

**Issue by BFFBern** [bkd-mba-fbi/kursausschreibung#176]
Bei den internen Kursen, wird öfters die Anmeldung nicht abgeschlossen.
Da keine Personendaten einzugeben sind, wird nicht realisiert, dass erneut auf Anmelden geklickt werden muss.
Könnte man den Text "Ihe Anmeldung wird gemäss Ihrem Login erstellt..." etwas hervorheben und ev. den senden Button umbenennen auf Bestätigen.

![image](https://github.com/bkd-mba-fbi/kursausschreibung/assets/77681704/080e1e04-daf2-4396-a2ec-a335ca649dce)

Umsetzung:
<img width="612" alt="image" src="https://github.com/user-attachments/assets/027b6ff8-af37-4f27-84d9-eed545e94c57">

**Comment by schefbi** [comment]
@fbufbi Was meinst du wie soll ich das umsetzten? Dieser Issue tritt nur in Evento Portal auf. Wollen wir diesen dort lösen oder hier im Kursauschreibungsmodul?

Mein Vorschlag. Den Text ergänzen und die class `.uk-text-warning` hinzufügen.

![Image](https://github.com/user-attachments/assets/50587efe-ac5f-49f1-a04a-ab28fbe81b75)

**Comment by fbufbi** [comment]
@schefbi Finde ich eine gute Lösung, und ich bin erst kürzlich über dieses "null" gestolpert - super, wenn es verschwindet.
Ich würde den Text so schreiben (zurzeit steht 3x "anmelden"):
- de: Bitte klicken Sie auf die Schaltfläche «Anmelden», um Ihre Anmeldung zu bestätigen und abzuschliessen. 
- fr: Veuillez cliquer sur le bouton "Inscription" pour confirmer et finaliser votre inscription.
