### ISSUE TITLE
Lifecycle Kursausschreibung

### ISSUE THREAD

**Issue by hupf** [bkd-mba-fbi/kursausschreibung#180]
- Grundsätzlich die Frage klären: Migrieren oder neu entwickeln oder ...?
  - Wird von Schulen standalone embedded, deshalb Integration in Webapp-Schulverwaltung nicht möglich?
- Ember aktualisieren von 3.x auf aktuellste Version (5.x?)
  - @schefbi hat einen lokalen Branch für 3.19 > 3.27 (noch ein paar Deprecation Warnings offen)
  - Siehe https://deprecations.emberjs.com/v3.x
- Alle anderen Dependencies:
  - Sind die verwendeten Dependencies noch alle maintained?
  - Dependencies aktualisieren oder ersetzen 
- ...

Varianten:
- Ember-Upgrade nach Version 5.x
  - kein Ember-Know-How vorhanden
  - Aufwand schwer abschätzbar, wahrscheinlich relativ hoch
- Neubau mit Angular
  - Know-How vorhanden (entspricht dem Webapp-Stack)
  - Umfang/Funktionalität der Applikation unklar
  - Durch die Integration in Schulverwaltung könnten viele Synergien genutzt werden, was sind die Einschränkungen berzüglich Embedding?

**Comment by fbufbi** [comment]
Wir ziehen den Task zurück.
Grund: Die Variante Neubau wäre v.a. ein Thema für euch, nicht aber für uns. Beim Ember Upgrade ist der Aufwand für euch (verständlicherweise) schwierig einzuschätzen. Das Knowhow zu Ember ist bei euch nur noch spärlich vorhanden.
