### ISSUE TITLE
datepicker from uikit

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#2]
Implement datepicker from uikit. So that not in every browser different style.

**Comment by schefbi** [comment]
**Internet Explorer**
No implementation

**Edge**
![grafik](https://user-images.githubusercontent.com/41326409/45208204-579df200-b28a-11e8-8f03-660273f5cb27.png)

**Firefox**
![grafik](https://user-images.githubusercontent.com/41326409/45208194-4ead2080-b28a-11e8-93ff-7478b01c923b.png)

**Chrome**
![grafik](https://user-images.githubusercontent.com/41326409/45208154-376e3300-b28a-11e8-9e09-4950bc4bfc4c.png)

**Comment by cravay** [comment]
uikit 3 doesn't have a datepicker.

we could use a datepicker library. examples:
https://flatpickr.js.org/
https://fengyuanchen.github.io/datepicker/
http://t1m0n.name/air-datepicker/docs/

we could also use a datepicker polyfill and use the native datepicker where it is available.
this should work better with autofill and on mobile devices but the datepicker doesn't
look the same everywhere. examples:
https://github.com/brianblakely/nodep-date-input-polyfill
https://github.com/chemerisuk/better-dateinput-polyfill

what do you think?

**Comment by schefbi** [comment]
we'll make a decision later.

**Comment by schefbi** [comment]
Wird verworfen.
