### ISSUE TITLE
Nach EventCodes filtern

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#33]
Es soll möglich sein nach EventCodes auf den routen `AreaOfEducation` und `EventCategory` zu filtern. Es sollen nur die Codes angezeigt werden für die es in der route auch events gibt.

Rest Api Endpunkt `/EventCodes/`

**Mögliche Darstellung**
![grafik](https://user-images.githubusercontent.com/41326409/55250717-22211c00-524f-11e9-8c87-5b8388e3d96e.png)

https://getuikit.com/docs/filter

In Mobile Modus muss die Code Filterung ausgeblendet werden, weil sonst die Übersichtlichkeit verloren geht.

### Umsetzung

- [x] settings.initialListFilters.codeIds 
- [x] Code können via local Datei übersetzt werden, weil das Backend diese nicht übersetzten kann
- [x] Wenn nur ein Code vorhanden wird die Paginierung ignoriert.
- [x] Möglich via Params zu filtern

![image](https://user-images.githubusercontent.com/41326409/128239061-5b258816-246f-44b8-9b3c-7bb075ba98f3.png)

**Comment by schefbi** [comment]
@ursbraem Was meinen sie zu diesem Vorschlag? Oder wie würden Sie das umsetzen?

**Comment by ursbraem** [comment]
Wir benötigen keine Knöpfe / Interaktionen. Gemeint wäre folgendes.

In der Response bräuchte es diese "Eventcodes":

```
  {
    ...,
    "EventCodes": 1234,
    ...
  },
```

Dann könnten wir einen zusätzlichen `InitialListFilter` machen:

```
  "initialListFilters": {
    "HostIds": null,
    "EventCategoryIds": null,
    "EventLevelIds": null,
    "EventTypeIds": null,
    "StatusIds": null,
    "EventCodes": 1234
  },
```

Grund: Die EventCategories decken sich nicht immer mit der gewünschten Präsentation. Dazu seien eben früher (?) die EventCodes genutzt worden, quasi für ein von der internen Kategorisierung unabhängiges "Tagging". Dies sei aber nicht mehr möglich. Was ich auch daran gesehen habe, dass die EventCodes nicht in der Response sind.

**Comment by schefbi** [comment]
@ursbraem Ok ich verstehe. Früher war es so das sie diese im UI filtern konnten. Wie ich es aufgezeigt habe. Wir müssen wohl beide Varianten anbieten. 

* Ein event kann 1-n codes zugewiesen haben
* Eine event kann nur 1 EventCategory (1:1) zugewiesen haben

So ist es möglich ein event in verschieden Bereichen anzuzeigen.

**Beispiel:**
SIZ Kurs (Kategorie: Informatik; Codes: Erwachsenenbildung, Freifachkurse)

**Comment by ursbraem** [comment]
Kleines Heads-up: die Funktion ist nicht mehr so extrem dringlich für den Kunden, da sie nun die Kategorien schon angepasst haben. Sie sind es sich aber noch am überlegen.
