### ISSUE TITLE
Datumsangaben mit Wochentag

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/kursausschreibung#60]
D. Williner, BSLB: Datumsangaben wie beim "Datum", der "Anmeldefrist" und dem "Kalendereintrag" sollen mit dem Wochentag ergänzt werden, z.B. **Mittwoch, 16.10.2019**

![image](https://user-images.githubusercontent.com/49237948/67004861-8d461900-f0e1-11e9-8afa-d14730373be5.png)

Testen ob die Lib das kann? Wenn ja bitte Kurzname Mo, Di, Mi usw.  

Gemäss [date-fns](https://date-fns.org/v2.15.0/docs/format) unit EEEEEE

**Comment by schefbi** [comment]
Test OK
