### ISSUE TITLE
Anzahl freier Plätze nach Ablauf der Anmeldefrist ausblenden

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/kursausschreibung#61]
D. Williner, BSLB: Nach Ablauf der Anmeldefrist soll die Anzahl freier Plätze nicht mehr angezeigt werden
![image](https://user-images.githubusercontent.com/49237948/67004962-c1213e80-f0e1-11e9-9383-2ed292081e28.png)

Konfigeintrage erstellen `badgeFreeSeats.subscriptionYellowDisable: false`

**Comment by schefbi** [comment]
Test OK
