### ISSUE TITLE
Sommer- winterzeit Problem bei Anzeige

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#62]
Die erste Lektion ist noch in der Sommerzeit wird mit einer Stunde mehr angezeigt. Ist möglichweise eine Problem mit der Lib [date-fns](https://date-fns.org/v1.30.1/docs/format)

![grafik](https://user-images.githubusercontent.com/41326409/67474942-942ad980-f655-11e9-8ceb-3c1e60fdcdfd.png)

![grafik](https://user-images.githubusercontent.com/41326409/67475039-b7558900-f655-11e9-944c-7b48fec8a3ec.png)

**Comment by schefbi** [comment]
@cravay Die BFF hat folgendes gemeldet. Beim Kurs folgendem noch aktiven Kurs ist das Problem auch vorhanden. Kannst du das bitte einmal analysieren?
https://www.bffbern.ch/weiterbildung-und-kurse/weiterbildung/weiterbildungskurse#/weiterbildung/wb_einb_k.gp/55882

**Comment by cravay** [comment]
@schefbi Der Bug wurde in der version 2.0.0 behoben (Siehe [Changelog](https://date-fns.org/v2.0.0/docs/Change-Log)). Ich habe die Version aktualisiert und den Code für die neue Version angepasst.

Ich habe gerade leider keine appConfig zur Hand und konnte deshalb den Fix noch nicht umfassend testen. In Chrome 77  auf dem Kurs auf bffbern.ch scheint er zu funktionieren.

**Comment by cravay** [comment]
Ich konnte es nicht mehr einrichten, ich glaube meine AppConfig ist veraltet.

**Comment by schefbi** [comment]
Ich werde es testen.

**Comment by cravay** [comment]
@schefbi Danke. Ich habe noch einen Fehler bei den date-helpers behoben.

Ich befürchte, dass aufgrund dieses Fehlers seit kursausschreibung 2.0.0 Daten (dates) vom Formular nicht mehr zum Server gesendet werden.

Kannst du bitte testen, ob es jetzt funktioniert (auch in IE, da das dort anders gehandhabt wird)?

**Comment by cravay** [comment]
Mit fd276ce wurde ein Bug eingeführt, siehe https://github.com/erz-mba-fbi/kursausschreibung/pull/68#issuecomment-573742575.

> 
> 
> > This shouldn't have happened. Did these errors occur while you were building the project? Have you tried to run `npm install` to update the dependencies?
> 
> Yes I have. I get an error when running ember serve and also in the frontend/dev.console.
> 
> ![Bildschirmfoto von 2020-01-13 17-12-30](https://user-images.githubusercontent.com/1239297/72271972-27a5f200-3628-11ea-8493-40536b9b1f7b.png)
> ![Bildschirmfoto von 2020-01-13 17-12-52](https://user-images.githubusercontent.com/1239297/72271982-2bd20f80-3628-11ea-95af-e501d8ef7bb1.png)
> ![Bildschirmfoto von 2020-01-13 17-13-08](https://user-images.githubusercontent.com/1239297/72271991-2e346980-3628-11ea-8148-fbae67f6474d.png)

**Comment by AramLoosman** [comment]
Dieses Problem besteht noch immer bei aktuellen Kursen welche über die Zeitumstellungsgrenze hinaus gehen. 
https://www.bffbern.ch/weiterbildung-und-kurse/weiterbildung/weiterbildungskurse#/weiterbildung/wb_einb_k.gp/55882
Wann wird die korrigierte Version released? Oder lohnt es sich, das manuell zu fixen?

**Comment by cravay** [comment]
Der Bug von https://github.com/bkd-mba-fbi/kursausschreibung/issues/62#issuecomment-574206342 sollte nicht mehr auftreten. Ich habe den neusten [`develop`-Build](https://bkd-mba-fbi.github.io/kursausschreibung/kursausschreibung.zip) mit einer Browser-Erweiterung in die BFF-Seite injected und die Daten wurden korrekt angezeigt.

![image](https://user-images.githubusercontent.com/11135559/88015996-c43ed480-cb22-11ea-8c35-ecb68ca75021.png)

> Wann wird die korrigierte Version released? 

@schefbi Was ist geplant?

> Oder lohnt es sich, das manuell zu fixen?

Die `develop`-Version könnte verwendet werden. Diese ist bis auf die neue `date-fns`-Version identisch zur `master`-Version ([master...develop](https://github.com/bkd-mba-fbi/kursausschreibung/compare/master...develop)). Sie wurde aber noch nicht ausgiebig getestet.

**Comment by schefbi** [comment]
@AramLoosman und @cravay : Momentan ist Evento 2020.R1 in der Testphase. Danach möchten wir eine neu Version des Moduls deployen. 

@cravay Wir sollten einmal wieder alle dependencies aktualisieren?

**Comment by cravay** [comment]
@schefbi Ich habe `npm audit fix` und `npm update` auf dem `develop`-Branch ausgeführt. Das Projekt lässt sich noch builden und es sollten keine "breaking changes" eingeführt worden sein.

**Comment by schefbi** [comment]
@cravay Ich habe Heute den letzten Build einmal integriert mit folgendem Fehler beim laden des Moduls. Sagt dir das etwas?
![grafik](https://user-images.githubusercontent.com/41326409/94574523-86250600-0273-11eb-97d4-cdbcdbad3bc2.png)

**Comment by cravay** [comment]
@schefbi Dieser Fehler ist bei mir nicht aufgetreten. Es scheint ein Problem beim Parsen eines Datums zu geben. Welchen Mandanten verwendest du?

**Comment by schefbi** [comment]
@cravay Ja z.B. BsInforama oder auch BsBZI.

**Comment by schefbi** [comment]
Das Problem ist das Datum mit Value null als Invalid ab Version angeschaut werden. https://date-fns.org/v2.0.0-alpha.26/docs/Upgrade-Guide. Das Problem tritt in addDisplayData(event) auf.

**Comment by schefbi** [comment]
@cravay Ich habe es probiert zu fixen. Was meinst du dazu?

**Comment by cravay** [comment]
@schefbi Sieht gut aus.

**Comment by schefbi** [comment]
Test Ok
