### ISSUE TITLE
Externer Link statt Anmeldung

### ISSUE THREAD

**Issue by ursbraem** [bkd-mba-fbi/kursausschreibung#67]
Es gibt Fälle, in denen der Kurs via Evento verwaltet wird, aber die Anmeldung ausserhalb erfolgt. Ist es möglich, einen "Anmelden" Link einzugeben, der eine URL auf der Website beinhaltet, die man klicken kann? Beispiel: https://www.oda-soziales-bern.ch/weiterbildung/8062 ganz unten

**Lösung:**

- [x] Event Text 13 eine URL vorhanden wird diese beim Anmelde Button hinterlegt `target:"_blank"`

- [x] Freie Plätze counter wird ausgeblendet

**Comment by schefbi** [comment]
@fbufbi Ist die Lösung für dich so plausibel?

**Comment by cravay** [comment]
@schefbi Kannst du bitte ein Testevent dafür einrichten? Meinst du mit "Event Text" die Antwort vom `/EventTexts`-Endpunkt?

**Comment by schefbi** [comment]
@cravay  Korrekt genau /EventText/. Auf dem Event 2517 habe ich ein Link ergänzt.

**Comment by cravay** [comment]
@schefbi Ich habe das Feature implementiert. Die Status-Lampen werden noch wie bisher angezeigt.

**Comment by ursbraem** [comment]
Danke!

**Comment by nisasche** [comment]
Ich habe noch ein Bug gefunden. 
instanz: BsInforama

![grafik](https://user-images.githubusercontent.com/36672237/100997872-1d9c2300-355b-11eb-92a3-084ae08d47a5.png)

**Comment by cravay** [comment]
@nisasche Danke für den Bug-Report. Jetzt sollte es funktionieren.
