### ISSUE TITLE
Typeahead PostalCodes (PLZ, Ort)

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/kursausschreibung#75]
Der Endpunkt `GET /PostalCodes/` soll im JSModule umgesetzt werden
Beispiel: Response Model mit Filterung PLZ: `GET /PostalCodes/?filter.Code=~380*`

Wenn PLZ im Typeahead ausgewählt wird soll der Ort automatisch gesetzt werden

**Comment by schefbi** [comment]
Test OK
