### ISSUE TITLE
Anmeldedetails mit Datum werden nicht übertragen -> Datentyp "Datum" gespeichert werden. Parameter name: value Actual value was L.

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#81]
Wenn eine Anmeldung auf einen Anlass mit Datum getätigt werden muss wird das Datum nicht `yyyy-mm-dd `über geben sondern als `L`.

*409 Fehlermeldung*
`Anmeldung fehlgeschlagen. Die Anmeldung auf "1F_HOL_BRANF_S1-2020/2021-1a (Brandschutz Fortsetzung S1-2020/2021-1a)" konnte nicht erstellt werden. Der Wert des Anmeldedetails Nr. 1210 kann nicht als Datentyp "Datum" gespeichert werden. Parameter name: value Actual value was L.`

Tritt nur in Chrome auf. IE11 funktioniert er.

**Comment by cravay** [comment]
Das Problem sollte mit d98395f gefixt worden sein (Siehe https://github.com/bkd-mba-fbi/kursausschreibung/issues/62#issuecomment-551023966 und commit message).

**Comment by schefbi** [comment]
Test OK
