### ISSUE TITLE
Was ist zu machen, damit das Modul SEO 

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#84]
Was ist zu machen, damit das Modul eingebettet werden kann und dennoch Suchmaschienenoptimiert ist.

https://developers.google.com/search/docs/guides/javascript-seo-basics?hl=de

Mit json-ld können JS Daten für SEO strukturiert werden > https://json-ld.org/  > Product https://schema.org/Product

[json-ld Playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22gr%22%3A%22http%3A%2F%2Fpurl.org%2Fgoodrelations%2Fv1%23%22%2C%22pto%22%3A%22http%3A%2F%2Fwww.productontology.org%2Fid%2F%22%2C%22foaf%22%3A%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%22%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22foaf%3Apage%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22gr%3AacceptedPaymentMethods%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22gr%3AhasBusinessFunction%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22gr%3AhasCurrencyValue%22%3A%7B%22%40type%22%3A%22xsd%3Afloat%22%7D%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fcars%2Ffor-sale%23tesla%22%2C%22%40type%22%3A%22gr%3AOffering%22%2C%22gr%3Aname%22%3A%22Used%20Tesla%20Roadster%22%2C%22gr%3Adescription%22%3A%22Need%20to%20sell%20fast%20and%20furiously%22%2C%22gr%3AhasBusinessFunction%22%3A%22gr%3ASell%22%2C%22gr%3AacceptedPaymentMethods%22%3A%22gr%3ACash%22%2C%22gr%3AhasPriceSpecification%22%3A%7B%22gr%3AhasCurrencyValue%22%3A%2285000%22%2C%22gr%3AhasCurrency%22%3A%22USD%22%7D%2C%22gr%3Aincludes%22%3A%7B%22%40type%22%3A%5B%22gr%3AIndividual%22%2C%22pto%3AVehicle%22%5D%2C%22gr%3Aname%22%3A%22Tesla%20Roadster%22%2C%22foaf%3Apage%22%3A%22http%3A%2F%2Fwww.teslamotors.com%2Froadster%22%7D%7D)

**Comment by schefbi** [comment]
@cravay Kannst du das einmal prüfen. Was alles geändert werden muss, damit Kurse in Google Suchmaschinen gefunden werden?

**Comment by cravay** [comment]
@schefbi Ich glaube das grösste Problem sind die URLs. Google rät davon ab Fragment-URLs zu verwenden:

[![image](https://user-images.githubusercontent.com/11135559/94343786-f08f3980-001a-11eb-882c-bfd50583c616.png)](https://developers.google.com/search/docs/guides/fix-search-javascript)

Um in Ember auf die History-API umzusteigen, reicht es in [environment.js](https://github.com/bkd-mba-fbi/kursausschreibung/blob/master/config/environment.js) den `locationType` auf `'history'` zu setzen. Dies würde aber erfordern, dass auf dem Server URLs [umgeschrieben](https://de.wikipedia.org/wiki/Rewrite-Engine) werden.

Wenn du dich als Besitzer einer Kursausschreibung-Seite ausweist, kannst du die  [Google Search Console](https://search.google.com/search-console/about) verwenden um zu schauen, welche URLs indexiert werden.

**Comment by cravay** [comment]
Die Weiterleitung zum OAuth-Server scheint die Indexierung auch zu verhindern. Bei https://www.bffbern.ch/weiterbildung/kurse ist `useAutoLogin` `false` und zumindest die Startseite des Moduls scheint indexiert zu werden. Bei https://www.bzemme.ch/kurseweiterbildung ist `useAutoLogin` `true` und nicht einmal die Startseite des Moduls wurde von Google indexiert.

**Comment by schefbi** [comment]
@cravay Merci, ich werde das einmal testen.

**Comment by schefbi** [comment]
@ursbraem: 
Aufgrund von Rückmeldungen von Schulen habe mich mit dem Thema Javascript apps und «Search Engine Optimization» auseinander gesetzt. Nun habe ich ein Lösung gefunden wie es möglich ist das auch dynamische JS Apps von Suchmaschinen gefunden werden. Im untenstehende Link habe ich Ihnen einen Test bereitgestellt der alle Kurs der BFF in einem script element type="application/ld+json" darstellt was von Suchmaschienen wie Google bevorzugt wird. 

[google > test/rich-results](https://search.google.com/test/rich-results/result/r%2Fcourses?id=iJnK1T1zc3jAtGVJBj7l3A)

Ich haben das so in der app umgesetzt, dass es auf der Seite wo das Modul implementiert ist immer dieses Element mit allen Kursen in den head der Seite integriert. Wenn Sie interessiert sind das einmal beim BFF zu integrieren um zu prüfen ob das auch wirklich funktioniert. Können Sie das mit dem neusten [Build](https://bkd-mba-fbi.github.io/kursausschreibung/kursausschreibung.zip) testen.

Grüsse Sandro Scheidt

**Comment by ursbraem** [comment]
Genial! Diese Frage stellen wir uns auch schon lange. Ich schlage es Elsbeth vor.

**Comment by BFFBern** [comment]
@schefbi Aram hat am Do. 5.5.22, den neusten Build gemäss Gemini Ticket [22621](https://erz.zubler.ch/workspace/219/item/22621) installiert. Ist das SEO Modul darin bereits enthalten? Ich habe keine Versionierung gefunden? gemäss [Test](https://search.google.com/test/rich-results/result?id=Dst30BMe4xuXy29m5QuBqg) noch nicht.

**Comment by ursbraem** [comment]
@BFFBern Die Version ist zuunterst im kursausschreibung.json 

@schefbi der Release von https://bkd-mba-fbi.github.io/kursausschreibung/kursausschreibung.zip ist noch kein offizieller Release, richtig?

Auf https://www.bffbern.ch/typo3conf/ext/sitepackage/Resources/Public/Evento/test/assets/kursausschreibung.js ist im Moment der neuste Build ab Github drin. Das ist anscheinend nicht die neuste Version, denn sie enthält nicht das gewünschte `application/ld+json`

PS @schefbi Können die [Fragment-URLs](https://github.com/bkd-mba-fbi/kursausschreibung/issues/84#issuecomment-699509606) trotzdem weiter verwendet werden?

**Comment by schefbi** [comment]
@ursbraem  

> @BFFBern Die Version ist zuunterst im kursausschreibung.json
> 
> @schefbi der Release von https://bkd-mba-fbi.github.io/kursausschreibung/kursausschreibung.zip ist noch kein offizieller Release, richtig?
> 

Korrekt, er beinhaltet folgende commits https://github.com/bkd-mba-fbi/kursausschreibung/pull/146

> Auf https://www.bffbern.ch/typo3conf/ext/sitepackage/Resources/Public/Evento/test/assets/kursausschreibung.js ist im Moment der neuste Build ab Github drin. Das ist anscheinend nicht die neuste Version, denn sie enthält nicht das gewünschte `application/ld+json`
> 

Das ist nicht der neuste build wenn ich den build herunterlade ist alles korrekt vorhanden > https://bkd-mba-fbi.github.io/kursausschreibung/kursausschreibung.zip


> PS @schefbi Können die [Fragment-URLs](https://github.com/bkd-mba-fbi/kursausschreibung/issues/84#issuecomment-699509606) trotzdem weiter verwendet werden?

Es wird immer noch via fragment-url gearbeitet.

**Comment by schefbi** [comment]
@BFFBern 

> @schefbi Aram hat am Do. 5.5.22, den neusten Build gemäss Gemini Ticket [22621](https://erz.zubler.ch/workspace/219/item/22621) installiert. Ist das SEO Modul darin bereits enthalten? Ich habe keine Versionierung gefunden? gemäss [Test](https://search.google.com/test/rich-results/result?id=Dst30BMe4xuXy29m5QuBqg) noch nicht.

Diese issues sind alle in diesem Build vorhanden. https://github.com/bkd-mba-fbi/kursausschreibung/pull/146

**Comment by BFFBern** [comment]
@schefbi Aram hat Build Version v4_3.3.3 zum Testen installiert. Wir werden dies gerne mit dem nächsten Release testen, sonst verliere ich den Überblick. Elsbeth

**Comment by schefbi** [comment]
jsonld wurde umgesetzt
