### ISSUE TITLE
Tooltip Status wird nicht angezeigt

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#86]
Der Tooltip bei der Statusampel wird nicht angezeigt. Nur Evento Web
![grafik](https://user-images.githubusercontent.com/41326409/94670917-752bd180-0313-11eb-9fcf-abaffe92c292.png)

**Comment by cravay** [comment]
@schefbi Bei mir schon. Welchen Mandanten verwendest du?

![image](https://user-images.githubusercontent.com/11135559/94742569-31b67f00-0376-11eb-80f6-60d6b2a2e351.png)

**Comment by schefbi** [comment]
@cravay Das Problem besteht nur in EventoWeb. Ich muss das dort beheben.

**Comment by schefbi** [comment]
bug fix in EventoWeb
