### ISSUE TITLE
Weitere Personen anmelden

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#87]
Kunden wünschen aufgrund COVID-19 Schutzkonzept. Mehrere Personen in der gleichen Anmeldung zu erfassen, bei Anlässen die ganze Familien oder Gruppen angemeldet werden können, damit Personalien und die Anzahl Teilnehmer/innen kontrolliert werden kann.

**LoginForm Erweiterung:**

1. - [x]  Wenn Anmeldedatail Id 10893 vorhanden wird diese am ende angezeigt. Das Anmeldedetail ist als Ganzzahl definiert und soll sobald grösser 0 weiter SubscriptionForms anzeigen mit icon 
![image](https://user-images.githubusercontent.com/41326409/95210583-f095f300-07eb-11eb-9260-542d184fd505.png)

2. - [x] Für jede Person ein Überschrift (Person 1, Person 2 usw.), damit es besser abgetrennt ist.
![image](https://user-images.githubusercontent.com/41326409/99413936-9615a980-28f6-11eb-8337-6d7bfc4f375a.png)

3. - [x] Wenn beim Button `weitere Person anmelden` die Freien Plätze erreicht sind muss ein Fehler kommen

4. - [x]  Die FormFields `formFieldsMorePersons` sollen pro Anlasstyp definiert werden können. Wenn nicht definiert Fallback auf `formFields`
5. - [x] Alle Anmeldedetails die die erste Person angegeben hat werden übernommen und können überschrieben werden.

**Validierung**
- [x] Wird der `dataType=email` auch bei den weiteren Personen angezeigt. Muss validiert werden ob die Mailadresse nicht mehrfach vorhanden ist. Wenn ja muss einen Fehlermeldung erscheinen `Die Mail muss unterschiedlich sein, ansonst kann das Formular nicht übermittelt werden.`

**Speicherung**
- [x] Alle Personen speichern
- [x] Alle Anmeldungen speichern
- [x] Bei einem Fehler zurück zum SubscriptionFrom

**Comment by schefbi** [comment]
@cravay Auf PROD BsTEST ist auf dem Anlass Id 2517 das Anmeldedetail erfasst. Morgen werde ich es noch auch BKT erfassen.

**Comment by cravay** [comment]
@schefbi Ich habe die Branch [feature/subscribe-multiple-people](https://github.com/bkd-mba-fbi/kursausschreibung/tree/feature/subscribe-multiple-people) erstellt und habe mit der Implementierung dieses Features begonnen. Ich habe noch ein paar Fragen.

<hr>

Ich habe Buttons hinzugefügt, mit der Personen hinzugefügt und entfernt werden können (siehe Bild). Ist das so in Ordnung?
![image](https://user-images.githubusercontent.com/11135559/99302042-1b458380-284f-11eb-8a24-2b776306fab1.png)

<hr>

Soll die Einstellung `formFieldsMorePersons` verschieden sein für die verschiedenen Event-Typen?

<hr>

> Wenn Anmeldedatail Id 10893 vorhanden wird diese am ende angezeigt. Das Anmeldedetail ist als Ganzzahl definiert und soll sobald grösser 0 weiter SubscriptionForms anzeigen mit icon

Welcher Wert muss grösser als 0 sein? Gibt die zu sende Zahl an, wie viele weitere Anmeldungen getätigt werden?

<details>
  <summary>Das Subscription-Detail</summary>
  
  ```json
	{
		"Id": "0_10893",
		"SubscriptionId": 0,
		"VssId": 10893,
		"EventId": 2517,
		"OpenInvoiceBookingId": null,
		"BookingType": null,
		"DropdownItems": null,
		"EnteringType": "",
		"IdPerson": 0,
		"IsValidated": false,
		"IsValidationMessage": false,
		"IsValidationStatus": false,
		"Required": false,
		"ShowAsRadioButtons": false,
		"Sort": "010893",
		"Tooltip": null,
		"Value": null,
		"VssDesignation": "Weitere Personen anmelden",
		"VssStyleDescription": "Text",
		"VssStyle": "TX",
		"VssTypeId": 277,
		"VssType": "Int",
		"ReadOnly": false,
		"ValueRangeRegex": null,
		"ValueRangeError": null,
		"MaxLength": null,
		"MaxFileSize": null,
		"IdObject": "0_10893",
		"IdSubscription": 0,
		"IdEvent": 2517,
		"IdAnmeldeVSS": 10893,
		"AdWert": null,
		"VssBezeichnung": "Weitere Personen anmelden",
		"VssTypEx": 277,
		"AllowChanges": true,
		"VssInternet": "E",
		"HRef": "/restApi/SubscriptionDetails/0_10893"
	},
  ```
  
</details>
<hr>

Es ist nur noch ein Platz auf dem Event frei. Kannst du bitte die freien Plätze erhöhen, damit ich Test-Anmeldungen durchführen kann?

<hr>

Evtl. würde es sich doch lohnen, ein MS-Teams-Meeting zu machen.

**Comment by schefbi** [comment]
@cravay 

> Soll die Einstellung formFieldsMorePersons verschieden sein für die verschiedenen Event-Typen?

Korrekt gemäss Anforderung 3

> Welcher Wert muss grösser als 0 sein? Gibt die zu sende Zahl an, wie viele weitere Anmeldungen getätigt werden?

Korrekt bei jeder Anmeldung muss die Anzahl weiterer Personen im Subscription-Detail 10893 als Value mitgegeben werden.

Plätze auf 10 gestellt.

Ich habe noch 2 Anforderungen ergänzt 2 und 3.¨

Ruf mich doch an ich bin Do oder Fr gut erreichbar.

**Comment by schefbi** [comment]
@cravay  Ist das issue fertig? Kann ich testen oder ist noch etwas offen.

**Comment by cravay** [comment]
@schefbi Das Senden der Daten und die Bestätigungstabelle habe ich noch nicht aktualisiert. Ich werde das Issue auf Testing verschieben, wenn ich damit fertig bin. Ich habe jetzt gleich eine Prüfung, danach werde ich weiterarbeiten. Sorry, dass es so lange dauert.

**Comment by cravay** [comment]
@schefbi Die Anmeldung von weiteren Personen sollten jetzt gehen, soweit ich das testen konnte.

Die Felder können mit `formFields.[default/EventTypeId].additionalPeopleFields` angegeben werden.

Wenn möglich würde ich gerne nur noch so oft wie nötig mit dem Code für die Anmeldungen arbeiten.

> Alle Anmeldedetails die die erste Person angegeben hat werden übernommen und können überschrieben werden.

Diesen Teil konnte ich nicht umsetzen. Ich müsste noch wissen, wie angegeben werden soll, ob ein AD überschrieben werden soll oder nicht. Könnte diese Anforderung auch weggelassen werden? In der jetzigen Version haben alle Anmeldungen die gleichen Anmeldedetails.

**Comment by schefbi** [comment]
@cravay  Kein Problem. Ich habe das nun noch gemacht.
