### ISSUE TITLE
Wenn keine Kurs vorhanden springt die App auf die Startseite

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/kursausschreibung#89]
Die BFB meldet das wenn keine Kurse vorhanden sind. Das die App auf die Startseite verweist. Ist das ein Fehler in der App oder in der implementierung der App in die www.bfb-bielbienne.ch Seite?

https://www.bfb-bielbienne.ch/grundbildung/kurse/#/ausbildung

**Comment by schefbi** [comment]
@cravay Kannst du das einmal anschauen? Ich sehe den Fehler nicht.

**Comment by cravay** [comment]
@schefbi Ich glaube das Problem kommt vom `base`-Tag.

![image](https://user-images.githubusercontent.com/11135559/97670188-fb0f7980-1a85-11eb-86aa-2b712d5b01c9.png)

Dieses führt dazu, dass Anchor-Links nicht relativ zur aktuellen URL ermittelt werden ([siehe MDN-Eintrag zu `<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)):

![image](https://user-images.githubusercontent.com/11135559/97670295-314cf900-1a86-11eb-9c20-4fa41b0f2f6b.png)

Wenn Ember.js auf https://www.bfb-bielbienne.ch/grundbildung/kurse/#/ weiterleiten will, wird stattdessen auf https://www.bfb-bielbienne.ch/ weitergeleitet. 

Als Lösung könnte das `base`-Tag entfernt werden. Alternativ könnte auch die URL im `base`-Tag durch https://www.bfb-bielbienne.ch/grundbildung/kurse/ ersetzt werden.
