### ISSUE TITLE
Travis CI ablösen

### ISSUE THREAD

**Issue by cravay** [bkd-mba-fbi/kursausschreibung#91]
Travis CI wurde verkauft und wird wahrscheinlich nicht mehr lange kostenlos bleiben [[1](https://blog.travis-ci.com/2019-01-23-travis-ci-joins-idera-inc)] [[2](https://news.ycombinator.com/item?id=25338983)].

@schefbi Ich würde vorschlagen, dass wir auf [Github Actions](https://github.com/features/actions) umsteigen.

**Comment by schefbi** [comment]
@cravay  Ich habe das auch schon gesehen. folgende Aussage ist spannend. Es gibt OSS Only Credits die aber nur dur Travis-ci vergeben werden. Aber Travis-ci entscheidet welche public Repos OSS Credits erhalten. 

![image](https://user-images.githubusercontent.com/41326409/101758531-bb05d280-3ad8-11eb-896e-bc6b92958699.png)
https://docs.travis-ci.com/user/billing-overview/#usage---user-licenses

Wir können einmal migrieren und wenn unsere Credits aufgebraucht sind und wir keine OSS erhalten steigen wir um auf GitHub Actions.

Der Migration Tab ist sowieso noch in einer Beta Phase
![image](https://user-images.githubusercontent.com/41326409/101758653-e5579000-3ad8-11eb-91ad-460474a9672e.png)

**Comment by cravay** [comment]
@schefbi In Ordnung. Du kannst mir sagen, wenn ich bei etwas helfen kann.

**Comment by schefbi** [comment]
Erfolgreich mit GitHub Actions abgelöst.
